name: Process and Combine XML Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process_xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml

    - name: Run createXiIncludeFiles.py.py
      run: python createXiIncludeFiles.py

    - name: Check XIincludes directory
      run: |
        if [ -d "XIincludes" ]; then
          echo "XIincludes directory exists."
          ls -l XIincludes
        else
          echo "XIincludes directory does not exist."
          exit 1
        fi

    - name: Combine DITA files
      run: |
        if ls XIincludes/*.dita 1> /dev/null 2>&1; then
          echo "<root>" > combined.dita
          cat XIincludes/*.dita >> combined.dita
          echo "</root>" >> combined.dita
        else
          echo "No DITA files found in XIincludes directory."
          exit 1
        fi

    - name: Upload combined DITA file
      uses: actions/upload-artifact@v2
      with:
        name: combined-dita
        path: combined.dita
